/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package JFrames;

import PROG11_Ejer01_JOptionPane.BBDD;
import PROG11_Ejer01_JOptionPane.Cliente;
import PROG11_Ejer01_JOptionPane.Escritura;
import java.util.ArrayList;

/**
 *
 * @author IVAN
 */
public class JFramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form NewJFramePrincipal
     */
     
    static String devuelve;
     
    public JFramePrincipal() {
        initComponents();
        devuelve=BBDD.ConectarBBDD();
        jLabelComentarios.setText(devuelve);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jDialog1 = new javax.swing.JDialog();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonNuevoCliente = new javax.swing.JButton();
        jButtonNuevaEscritura = new javax.swing.JButton();
        jButtonRelacionarEcrituraClientes = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButtonVerClientes = new javax.swing.JButton();
        jButtonMuestraEscrituras = new javax.swing.JButton();
        jButtonMuestraRelacionEscrituraCliente = new javax.swing.JButton();
        jButtonMuestraClientesCompraVenta = new javax.swing.JButton();
        jButtonActualizaCliente = new javax.swing.JButton();
        jButtonActualizaEscritura = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButtonBorrarCliente = new javax.swing.JButton();
        jButtonBorrarEscritura = new javax.swing.JButton();
        jLabelComentarios = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaPrincipal = new javax.swing.JTextArea();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("TABLA CLIENTES");
        jButton2.setToolTipText("");
        jButton2.setActionCommand("ButtonCrearTablaClientes");
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearTablaClientes(evt);
            }
        });

        jButton3.setText("TABLA ESCRITURAS");
        jButton3.setToolTipText("");
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearTablaEscrituras(evt);
            }
        });

        jButton4.setText("TABLA ESCCLI");
        jButton4.setToolTipText("");
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearTablaEscCli(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("*** Crear tablas ***");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("*** Insertar datos ***");

        jButtonNuevoCliente.setText("NUEVO CLIENTE");
        jButtonNuevoCliente.setToolTipText("");
        jButtonNuevoCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonNuevoCliente.setSelected(true);
        jButtonNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoClienteActionPerformed(evt);
            }
        });

        jButtonNuevaEscritura.setText("NUEVA ESCRITURA");
        jButtonNuevaEscritura.setToolTipText("");
        jButtonNuevaEscritura.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonNuevaEscritura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevaEscrituraActionPerformed(evt);
            }
        });

        jButtonRelacionarEcrituraClientes.setText("RELACIONAR ESCRITURA & CLIENTES");
        jButtonRelacionarEcrituraClientes.setToolTipText("");
        jButtonRelacionarEcrituraClientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonRelacionarEcrituraClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelacionarEcrituraClientesActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("*** Mostrar datos ***");

        jButtonVerClientes.setText("VER CLIENTES");
        jButtonVerClientes.setToolTipText("");
        jButtonVerClientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonVerClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerClientesActionPerformed(evt);
            }
        });

        jButtonMuestraEscrituras.setText("VER ESCRITURAS");
        jButtonMuestraEscrituras.setToolTipText("");
        jButtonMuestraEscrituras.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonMuestraEscrituras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMuestraEscriturasActionPerformed(evt);
            }
        });

        jButtonMuestraRelacionEscrituraCliente.setText("VER RELACIONES ESCRITURA & CLIENTE");
        jButtonMuestraRelacionEscrituraCliente.setToolTipText("");
        jButtonMuestraRelacionEscrituraCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonMuestraRelacionEscrituraCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMuestraRelacionEscrituraClienteActionPerformed(evt);
            }
        });

        jButtonMuestraClientesCompraVenta.setText("VER CLIENTES HAN REALIZADO COMPRA-VENTA (CPVE)");
        jButtonMuestraClientesCompraVenta.setToolTipText("");
        jButtonMuestraClientesCompraVenta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonMuestraClientesCompraVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMuestraClientesCompraVentaActionPerformed(evt);
            }
        });

        jButtonActualizaCliente.setText("ACTUALIZAR CLIENTE");
        jButtonActualizaCliente.setToolTipText("");
        jButtonActualizaCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonActualizaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizaClienteActionPerformed(evt);
            }
        });

        jButtonActualizaEscritura.setText("ACTUALIZAR ESCRITURA");
        jButtonActualizaEscritura.setToolTipText("");
        jButtonActualizaEscritura.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonActualizaEscritura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizaEscrituraActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("*** Borrar datos ***");

        jButtonBorrarCliente.setText("BORRAR CLIENTE");
        jButtonBorrarCliente.setToolTipText("");
        jButtonBorrarCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonBorrarCliente.setSelected(true);
        jButtonBorrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarClienteActionPerformed(evt);
            }
        });

        jButtonBorrarEscritura.setText("BORRAR ESCRITURA");
        jButtonBorrarEscritura.setToolTipText("");
        jButtonBorrarEscritura.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonBorrarEscritura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarEscrituraActionPerformed(evt);
            }
        });

        jLabelComentarios.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabelComentarios.setForeground(new java.awt.Color(255, 0, 0));
        jLabelComentarios.setText("***");
        jLabelComentarios.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jTextAreaPrincipal.setColumns(20);
        jTextAreaPrincipal.setRows(5);
        jScrollPane1.setViewportView(jTextAreaPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonMuestraRelacionEscrituraCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonMuestraEscrituras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonVerClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonMuestraClientesCompraVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonRelacionarEcrituraClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButtonNuevaEscritura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonNuevoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButtonActualizaCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonActualizaEscritura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(jLabel1)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jButtonBorrarCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonBorrarEscritura, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelComentarios, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonNuevoCliente)
                            .addComponent(jButtonActualizaCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonNuevaEscritura)
                            .addComponent(jButtonActualizaEscritura))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRelacionarEcrituraClientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBorrarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBorrarEscritura)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonVerClientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonMuestraEscrituras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonMuestraRelacionEscrituraCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonMuestraClientesCompraVenta))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelComentarios, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCrearTablaClientes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearTablaClientes
        devuelve=BBDD.crearTablaClientes();
        jLabelComentarios.setText(devuelve);     
    }//GEN-LAST:event_jButtonCrearTablaClientes

    private void jButtonNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoClienteActionPerformed
        JFrameNuevoCliente jf=new JFrameNuevoCliente();
        jf.setVisible(true);
    }//GEN-LAST:event_jButtonNuevoClienteActionPerformed

    private void jButtonVerClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerClientesActionPerformed
        ArrayList<Cliente> clientes=BBDD.devuelveClientes();
        String devuelve="CLIENTES:\n";
        for(int i=0;i<clientes.size();i++){
            devuelve=devuelve+clientes.get(i).imprimeCliente()+"\n";
        }
        jTextAreaPrincipal.setText(devuelve);
    }//GEN-LAST:event_jButtonVerClientesActionPerformed

    private void jButtonActualizaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizaClienteActionPerformed
        JFrameActualizarCliente jf=new JFrameActualizarCliente();
        jf.setVisible(true);
    }//GEN-LAST:event_jButtonActualizaClienteActionPerformed

    private void jButtonBorrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarClienteActionPerformed
        JFrameBorrarCliente jf=new JFrameBorrarCliente();
        jf.setVisible(true);
    }//GEN-LAST:event_jButtonBorrarClienteActionPerformed

    private void jButtonCrearTablaEscrituras(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearTablaEscrituras
        devuelve=BBDD.crearTablaEscrituras();
        jLabelComentarios.setText(devuelve);
    }//GEN-LAST:event_jButtonCrearTablaEscrituras

    private void jButtonCrearTablaEscCli(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearTablaEscCli
        devuelve=BBDD.crearTablaEsccli();
        jLabelComentarios.setText(devuelve);
    }//GEN-LAST:event_jButtonCrearTablaEscCli

    private void jButtonNuevaEscrituraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevaEscrituraActionPerformed
        JFrameNuevaEscritura jf=new JFrameNuevaEscritura();
        jf.setVisible(true);
    }//GEN-LAST:event_jButtonNuevaEscrituraActionPerformed

    private void jButtonRelacionarEcrituraClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelacionarEcrituraClientesActionPerformed
        JFrameNuevaRelacionEscrituraCliente jf=new JFrameNuevaRelacionEscrituraCliente();
        jf.setVisible(true);
    }//GEN-LAST:event_jButtonRelacionarEcrituraClientesActionPerformed

    private void jButtonMuestraEscriturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMuestraEscriturasActionPerformed
        ArrayList<Escritura> escrituras=BBDD.devuelveEscrituras();
        String devuelve="ESCRITURAS:\n";
        for(int i=0;i<escrituras.size();i++){
            devuelve=devuelve+escrituras.get(i).imprimeEscritura()+"\n";
        }
        jTextAreaPrincipal.setText(devuelve);
    }//GEN-LAST:event_jButtonMuestraEscriturasActionPerformed

    private void jButtonMuestraRelacionEscrituraClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMuestraRelacionEscrituraClienteActionPerformed
        ArrayList<Escritura> escrituras=BBDD.devuelveEscrituras();
        ArrayList<Cliente> clientes=new ArrayList<Cliente>();
        String devuelve="REALACION ESCRITURAS->CLIENTES:\n";
        for(int i=0;i<escrituras.size();i++){
            devuelve=devuelve+escrituras.get(i).imprimeEscritura()+"\n";
            clientes=BBDD.devuelveClientesDeEscritura(escrituras.get(i));
            for(int j=0;j<clientes.size();j++){
                devuelve=devuelve+clientes.get(j).imprimeCliente()+"\n";
            }
            devuelve=devuelve+"\n";
        }
        jTextAreaPrincipal.setText(devuelve);
    }//GEN-LAST:event_jButtonMuestraRelacionEscrituraClienteActionPerformed

    private void jButtonMuestraClientesCompraVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMuestraClientesCompraVentaActionPerformed
        String devuelve="CLIENTES QUE HAN REALIZADO UNA COMPA-VENTA (CPVE):\n";
        ArrayList<Integer> codClientesCPVE=BBDD.devuelveCodigoClientesCPVE();
        for(int i=0;i<codClientesCPVE.size();i++){
            Cliente c=BBDD.devuelveCliente(codClientesCPVE.get(i));
            devuelve=devuelve+c.imprimeCliente()+"\n";
        }
        jTextAreaPrincipal.setText(devuelve);
    }//GEN-LAST:event_jButtonMuestraClientesCompraVentaActionPerformed

    private void jButtonActualizaEscrituraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizaEscrituraActionPerformed
        JFrameActualizarEscritura jf=new JFrameActualizarEscritura();
        jf.setVisible(true);
    }//GEN-LAST:event_jButtonActualizaEscrituraActionPerformed

    private void jButtonBorrarEscrituraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarEscrituraActionPerformed
        JFrameBorrarEscritura jf=new JFrameBorrarEscritura();
        jf.setVisible(true);
    }//GEN-LAST:event_jButtonBorrarEscrituraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonActualizaCliente;
    private javax.swing.JButton jButtonActualizaEscritura;
    private javax.swing.JButton jButtonBorrarCliente;
    private javax.swing.JButton jButtonBorrarEscritura;
    private javax.swing.JButton jButtonMuestraClientesCompraVenta;
    private javax.swing.JButton jButtonMuestraEscrituras;
    private javax.swing.JButton jButtonMuestraRelacionEscrituraCliente;
    private javax.swing.JButton jButtonNuevaEscritura;
    private javax.swing.JButton jButtonNuevoCliente;
    private javax.swing.JButton jButtonRelacionarEcrituraClientes;
    private javax.swing.JButton jButtonVerClientes;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelComentarios;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaPrincipal;
    // End of variables declaration//GEN-END:variables
}
