package ventanas;

import academiaMas.Alumno;
import academiaMas.CargarGuardar;
import academiaMas.Modulo;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author IVAN
 */
public class MenuPrincipal extends javax.swing.JFrame {
    private ArrayList<Alumno> listaAlumnos=new ArrayList<Alumno>();
    private ArrayList<Modulo> listaModulos=new ArrayList<Modulo>();
    static CargarGuardar<Alumno> cgAlumno=new CargarGuardar<Alumno>();
    static CargarGuardar<Modulo> cgModulo=new CargarGuardar<Modulo>();
    
    
    public MenuPrincipal() {
        initComponents();
    }
    
    //Añade Modulo a listaModulos
    public void añadirModulo(Modulo m){
        listaModulos.add(m);
    }
    //Devulve la dimensión de la listaModulos
    public int tamañoListaModulos(){
        return listaModulos.size();
    }
    //Devuelve un Modulo especificado por parámetro i
    public Modulo obtenerModulo(int i){
        return listaModulos.get(i);
    }
    
    //Añade Alumno a listaAlumnos
    public void añadirAlumno(Alumno a){
        listaAlumnos.add(a);
    }
    //Devulve la dimensión de la listaAlumnos
    public int tamañoListaAlumnos(){
        return listaAlumnos.size();
    }
    //Devuelve un Alumno especificado por parámetro i
    public Alumno obtenerAlumno(int i){
        return listaAlumnos.get(i);
    }

    
    //METODOS GET y SET
    public ArrayList<Alumno> getListaAlumnos() {
        return listaAlumnos;
    }
    public void setListaAlumnos(ArrayList<Alumno> listaAlumnos) {
        this.listaAlumnos = listaAlumnos;
    }
    public ArrayList<Modulo> getListaModulos() {
        return listaModulos;
    }
    public void setListaModulos(ArrayList<Modulo> listaModulos) {
        this.listaModulos = listaModulos;
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /*
    **********    
    CODIGO INTERFACE GRAFICA
    **********
    */

    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItemGuardarAlumno = new javax.swing.JMenuItem();
        jMenuItemCargarAlumno = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItemGuardarModulo = new javax.swing.JMenuItem();
        jMenuItemCargarModulo = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Añadir Alumno");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Añadir Módulo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Ver Alumno");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jMenu5.setText("Alumnos");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Añadir alumno");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Ver alumno");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenuItemGuardarAlumno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemGuardarAlumno.setText("Guardar alumno");
        jMenuItemGuardarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGuardarAlumnoActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemGuardarAlumno);

        jMenuItemCargarAlumno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemCargarAlumno.setText("Cargar alumno");
        jMenuItemCargarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCargarAlumnoActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemCargarAlumno);

        jMenuBar2.add(jMenu5);

        jMenu6.setText("Módulos");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText("Añadir módulo");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem6);

        jMenuItemGuardarModulo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemGuardarModulo.setText("Guardar módulo");
        jMenuItemGuardarModulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGuardarModuloActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemGuardarModulo);

        jMenuItemCargarModulo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemCargarModulo.setText("Cargar módulo");
        jMenuItemCargarModulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCargarModuloActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemCargarModulo);

        jMenuBar2.add(jMenu6);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(288, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JDAñadirAlumno jf=new JDAñadirAlumno(this, true);
        jf.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JDAñadirModulo jf=new JDAñadirModulo(this, true);
        jf.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JDVerAlumno jf=new JDVerAlumno(this, true);
        jf.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JDAñadirAlumno jf=new JDAñadirAlumno(this, true);
        jf.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JDVerAlumno jf=new JDVerAlumno(this, true);
        jf.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        JDAñadirModulo jf=new JDAñadirModulo(this, true);
        jf.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItemGuardarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGuardarAlumnoActionPerformed
        JFileChooser jfcAbrir=new JFileChooser();
        int seleccion=jfcAbrir.showSaveDialog(this);
        if(seleccion==JFileChooser.APPROVE_OPTION){
            File fichero=jfcAbrir.getSelectedFile();
            if(cgAlumno.guardar(listaAlumnos, fichero)==true){
                JOptionPane.showMessageDialog(this, "Fichero guardado correctamente","Almacenamiento correcto",JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "Error al guardar el fichero","ERROR",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jMenuItemGuardarAlumnoActionPerformed

    private void jMenuItemGuardarModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGuardarModuloActionPerformed
        JFileChooser jfcAbrir=new JFileChooser();
        int seleccion=jfcAbrir.showSaveDialog(this);
        if(seleccion==JFileChooser.APPROVE_OPTION){
            File fichero=jfcAbrir.getSelectedFile();
            if(cgModulo.guardar(listaModulos, fichero)==true){
                JOptionPane.showMessageDialog(this, "Fichero guardado correctamente","Almacenamiento correcto",JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "Error al guardar el fichero","ERROR",JOptionPane.ERROR_MESSAGE);
            }  
        }
    }//GEN-LAST:event_jMenuItemGuardarModuloActionPerformed

    private void jMenuItemCargarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCargarAlumnoActionPerformed
        JFileChooser jfcAbrir=new JFileChooser();
        int seleccion=jfcAbrir.showSaveDialog(this);
        if(seleccion==JFileChooser.APPROVE_OPTION){
            File fichero=jfcAbrir.getSelectedFile();
            if((listaAlumnos=cgAlumno.cargar(fichero))!=null){
                JOptionPane.showMessageDialog(this, "Fichero cargado correctamente","Carga correcto",JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "Error al cargar el fichero","ERROR",JOptionPane.ERROR_MESSAGE);
            }   
        }
    }//GEN-LAST:event_jMenuItemCargarAlumnoActionPerformed

    private void jMenuItemCargarModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCargarModuloActionPerformed
        JFileChooser jfcAbrir=new JFileChooser();
        int seleccion=jfcAbrir.showSaveDialog(this);
        if(seleccion==JFileChooser.APPROVE_OPTION){
            File fichero=jfcAbrir.getSelectedFile();
            if((listaModulos=cgModulo.cargar(fichero))!=null){
                JOptionPane.showMessageDialog(this, "Fichero cargado correctamente","Carga correcto",JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "Error al cargar el fichero","ERROR",JOptionPane.ERROR_MESSAGE);
            }   
        }
    }//GEN-LAST:event_jMenuItemCargarModuloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItemCargarAlumno;
    private javax.swing.JMenuItem jMenuItemCargarModulo;
    private javax.swing.JMenuItem jMenuItemGuardarAlumno;
    private javax.swing.JMenuItem jMenuItemGuardarModulo;
    // End of variables declaration//GEN-END:variables
}
